#pragma once

typedef enum beer_err
{
	BEER_OK,
	BEER_ERR_INIT,
	BEER_ERR_NO_MEM,
	BEER_ERR_IO,

	BEER_ERR_FS_GENERIC,
	BEER_ERR_FS_NO_ENTRY,
	BEER_ERR_FS_NO_ACCESS,
	BEER_ERR_FS_NOT_A_DIR,
	BEER_ERR_FS_NOT_A_FILE,

	BEER_ERR_PY_INIT,
	BEER_ERR_PY_COMPILE,
	BEER_ERR_PY_EXEC,
	BEER_ERR_PY_BAD_SCRIPT,
} beer_err;
